### ISSUE TITLE
how to utilize a file with no class in index.js

### ISSUE THREAD

**Issue by mikecasey93** [jonathan-chin/mec-ttp-2021-winter#1]
I have a file that uses checkboxes but it includes no class based on the example form material.ui and don't know how to use it in index.js

**Comment by jonathan-chin** [comment]
Hi @mikecasey93 ,

generally the code you have in the function definition will go inside the class definition's `render()` function. however, if your code uses React hooks (which look like `useState()`) will need to be rewritten.
